### ISSUE TITLE
Is it a stable version?

### ISSUE THREAD

**Issue by github5546** [Akylas/conty#4]
Hello,

I'm not sure I use the good version because :

- I can't install it from f-droid. The only option I have is "Sharing"
- In obtainium, that's indicated like a fictive version (first time I see that)
- When I install it anyway, I can't give rights to access all files (the checkbox is grey)

Thx for the help

Edit : I'm on GrapheneOS

**Comment by farfromrefug** [comment]
@github5546 the last build seems to be broken in some ways:
* The reason why you might be only seeing sharing on f-droid is because only armv8 is published on izzydroid. armv7 is only on github. No real solution right now. Might be fixed in the future
* about obtainium what kind of fictive version does it give?
* i need to check this it should work, might be due to the last version being not "right". What s your android version?

**Comment by github5546** [comment]
![Screenshot_20241014-212736](https://github.com/user-attachments/assets/280b4dde-9f8c-4582-8f68-9ca70f4b8320)

I'm on Android 14

**Comment by github5546** [comment]
Sorry, mistake, I closed it

**Comment by farfromrefug** [comment]
@github5546 of the name in obtainium is because it reads my github tags for which i have a special format (because i release 3 differents apps: iOS, Android playstore, Android github). It might look weird but it should work within.
I am building a new version. Will test it and report that is correct!

**Comment by farfromrefug** [comment]
@github5546 here is a fixed version https://github.com/Akylas/conty/releases/tag/android%2Fgithub%2F1.5.5%2F18

**Comment by github5546** [comment]
It works. Thx!!
